DjangoApplication/blog/urls.py
from django.urls import path
from . import views
from .views import PostListView

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),        
]

DjangoApplication/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),  
    path('', include('registration.urls')),
    path('', include('blog.urls')),
    path('', include('artgallery.urls')),
    path('', include('courses.urls')),
    path('', include('offer.urls')),
    path('', include('chat.urls')),
    path('', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoApplication/blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # text = models.TextField()
    text = RichTextField(blank=True, null=True)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text






    

DjangoApplication/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from django.utils import timezone
from ckeditor.fields import RichTextField

class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    course_image = models.ImageField(null=True, blank=True, upload_to="images/courses/")
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('courses')

class Lesson(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/lessons/")
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    video = models.FileField(upload_to="videos", null=True, verbose_name="")
    lesson_date =  models.DateField(auto_now_add=True)
    course = models.CharField(max_length=255, null=True, blank=True)
    lesson_number = models.IntegerField()
    is_done = models.ManyToManyField(User, related_name='is_done', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses')

DjangoApplication/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Comment

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
        
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

    widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tytuł'}),
        'text': forms.Textarea(attrs={'class': 'form-control'}),
    }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

DjangoApplication/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, Comment
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .forms import NewUserForm
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class HomeView(ListView):
    model = Post
    template_name = 'posts.html'

def home(request):
    return render(request, 'blog/home.html')

class PostListView(ListView):
    queryset = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date').reverse()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post_list.html'

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date').reverse()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()    
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

DjangoApplication/blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Napisz komentarz</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

DjangoApplication/blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>
            {% block title %}
            My Site
            {% endblock %}
        </title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Merriweather&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
    </style>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/bc6eb907d9.js" crossorigin="anonymous"></script>
        <link href='{% static "css/blog.css" %}' rel="stylesheet">

    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        

        <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'offer' %}">Oferta</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course_list' %}">Kursy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post_list' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'artgallery' %}">Galeria</a>
                    </li>                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Kontakt</a>
                    </li>    

                    {% if user.is_authenticated %}      
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_account' %}">Twoje konto</a>
                    </li> 
                    {% endif %}
                    {% if user.is_authenticated and user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin_panel' %}">Panel admina</a>
                    </li>               
                    {% endif %}
                                       
                </ul>

                <ul class="nav navbar-nav my-2 my-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Witaj, </span> 
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link" href="/">{{ request.user.username }}</a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Wyloguj się</a>
                    </li>                    
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/register"><span class="glyphicon glyphicon-user"></span> Rejestracja</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login"><span class="glyphicon glyphicon-log-in"></span> Logowanie</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
          </nav>
          <br />
          <div class="container">
                {% block content %}
                {% endblock %}
        </div>
    </body>
</html>

DjangoApplication/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<br/><br/><br/>

<div class="row">
    <div class="col">
        <h1>Poznaj grafikę!</h1>
        <br/>
        <p class="lead text-justify">
            Szukasz grafiki dla siebie? Chcesz nauczyć się ją tworzyć lub udoskonalić swoje umiejętności?
            <br/>
            Trafiłeś w odpowiednie miejce!
            <br/><br/>
            Rozpoczynasz swoją przygodę z grafiką komputerową? Podoba Ci się, ale nie wiesz od czego zacząć?
            <br/> 
            Skorzystaj z oferty <strong><a href="{% url 'course_list' %}">kursów</a></strong> i wybierz ten, 
            który najbardziej pomoże Ci rozwinąć skrzydła.
            <br /><br/>
            Potrzebujesz grafiki do swojego biznesu? Chcesz upiększyć przestrzeń wokół <strong><a href="{% url 'artgallery' %}">oryginalną sztuką</a></strong>? 
            <br />Zapoznaj się z <strong><a href="{% url 'offer' %}">ofertą</a></strong> i napisz do mnie,
            a stworzymy wyjątkowy projekt specjalnie dla Ciebie.
        </p>
    </div>
    <div class="col">
        <img src="{% static 'images/Discuss talent requirements.png' %}" style="width:600px"/>
    </div>
</div>


<br/><br/><br/>
    <center><a href="{% url 'contact' %}">
        <button type="button" a href="{% url 'contact' %}" class="btn btn-outline-dark btn-lg">
            Skontaktuj się</button></a>
    </center>

    <br/><br/><br/>
    <small>System powstał na Wydziale Informatyki Politechniki Białostockiej.</small>


    
   


{% endblock %}

DjangoApplication/blog/templates/blog/paginator.html
<nav aria-label="Page navigation">

    <ul class="pagination">
        <li class="page-item">
            {% if page.has_previous %}
            <a class="page-link" href="?page={{ page.previous_page_number }}">
                <<
            </a>
            {% endif %}
        </li>
        <li class="page-item">
            <a class="page-link">
                 {{page.number}} / {{page.paginator.num_pages}}
            </a>
        </li>
        <li class="page-item">
            {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">
                >>
            </a>
            {% endif %}
        </li>
    </ul>
</nav>

DjangoApplication/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}        
        <a href="{% url 'post_edit' pk=post.pk %}" class="btn btn-outline-dark btn-sm" >Edytuj</a>
        <a href="{% url 'post_remove' pk=post.pk %}" class="btn btn-outline-dark btn-sm" >Usuń</a>
            {% if not post.published_date %}
                <a href="{% url 'post_publish' pk=post.pk %}" class="btn btn-outline-dark btn-sm" >Publikuj</a>
            {% endif %}
        {% endif %}
    {% endif %}
    
    <h1>{{ post.title }}</h1>
    <small>Autor: {{ post.author.first_name }} 
        {{ post.author.last_name }}
    </small>
    {% if post.published_date %}            
        <small>| {{ post.published_date|date:'M d, Y' }}</small>
    {% endif %}
    <br/>
    <hr>
    {{ post.text|safe }}    
    <br/><br/>
    <p><a href="{% url 'post_list' %}">Powrót</a></p>
    <br/>
    <h4>Komentarze:</h4>
    <p><a href="{% url 'add_comment_to_post' pk=post.pk %}">Napisz komentarz</a></p>
    
    {% for comment in post.comments.all %}    
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="p-3 mb-3 bg-light rounded">
            {% if not comment.approved_comment %}
                <a class="btn btn-outline-dark btn-sm mb-3" href="{% url 'comment_remove' pk=comment.pk %}">Odrzuć</a>
                <a class="btn btn-outline-dark btn-sm mb-3" href="{% url 'comment_approve' pk=comment.pk %}">Akceptuj</a>            
            {% endif %}
            <br/>
            <strong>{{ comment.author }}</strong> 
            <br/> 
            <small>{{ comment.created_date }}</small>   
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p> Nie ma jeszcze żadnych komentarzy :(</p>
    {% endfor %}
    

{% endblock %}

DjangoApplication/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    {% if request.user.is_superuser %}
    {% for post in posts %}
    <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
        <small>
            Edytowano: {{ post.created_date|date:'M d, Y' }}
        </small>
        <br/>
        <hr>
        <p>{{ post.text|slice:":200"|safe }}</p>
        <br/>
    {% endfor %}
    {% endif %}
{% endif %}
{% endblock %}

DjangoApplication/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block title %}
Dodaj post...
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
    {% if request.user.is_superuser %}
    <h1>Pisanie postu...</h1>
    <br/><br/>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
    <button type="submit" class="save btn btn-dark" style="float:left;">Zapisz post</button>
    {% else %}
        Brak dostępu!
    {% endif %}
    {% else %}
    Brak dostępu!
{% endif %}
{% endblock %}

DjangoApplication/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

<div class= "jumbotron">
    {% for post in posts %}        
        <h1 class="display-4">
            <a href="{% url 'post_detail' pk=post.pk %}">
                {{ post.title }}
            </a>
        </h1>
        <small>{{ post.published_date|date:'M d, Y' }} | 
        <a href="{% url 'post_detail' pk=post.pk %}">Komentarze: {{ post.approved_comments.count }}</a>
        </small>
        <br/>
        <hr>
        {{ post.body }}        
        <p>{{ post.text|truncatewords:30|safe }}</p>
        <br/>
    {% endfor %}
</div>

{% include 'blog/paginator.html' with page=page_obj %}

    
{% endblock %}